env:
- ARTIFACT_NAME="udhbwvst"
language: generic
services:
- docker
script:
  - docker build -t "skyfrk/udhbwvst:build" .
  - docker run -v ${TRAVIS_BUILD_DIR}/examples/full:/work skyfrk/udhbwvst:build latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -pdflatex=lualatex -shell-escape full.tex
  - docker run -v ${TRAVIS_BUILD_DIR}/examples/starter-advanced:/work skyfrk/udhbwvst:build latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -pdflatex=lualatex -shell-escape starter-advanced.tex
  - docker run -v ${TRAVIS_BUILD_DIR}/examples/starter-recommended:/work skyfrk/udhbwvst:build latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -pdflatex=lualatex -shell-escape starter-recommended.tex
before_deploy:
  - mkdir example
  - cp -r .vscode example
  - cp .gitignore example
  - cp build.sh example
  - cp build.ps1 example
  - cp .devcontainer.json example
  - echo "$ARTIFACT_NAME $TRAVIS_TAG Build $TRAVIS_BUILD_NUMBER" > version.txt
  - touch example/text.tex
  - touch example/literature.bib
  - zip -r ${ARTIFACT_NAME}-${TRAVIS_TAG}.zip src example install_udhbwvst_tl.ps1 install_udhbwvst_tl.sh version.txt -x src/.gitignore
deploy:
  provider: releases
  api_key:
    secure: jPoN6oP7p+u1u82rF+KyNa77i4Har2+8Bh9CJsK3/1lq2F36y3GnrA1eYLaBcY+ZUdvqYaf2TpVuJx/G6O1F4MgZwNTlSJPF4Ar+mKkcKL58nJpjhdgyGpC2mhzZ9rs34u6zyZ/pndC4aJx6yrRA1kWpFQYx/GDP21poNcdnSRIrMA2smcelakAAoV/LpQgKB4QRrLVfbirZxM4jk0xf5v0Z/2jIObMPXvS7aBCyUbrxp1iKaFNuu19JbMJHjKfLSt6CAaqCPqwl/WA7Qy2bhz6DGFnAaxcFXwcIfY7iSp4+yeV0wP/gfgrYQ8e1TgFFEq38sRPmK8qPzyLXRUvVuVJdNEuGQqWAPhgnmqR7JRMTpqUAPRbWLX0yrHEBpURF67dLP27aWmTAcFYqYhRZgwpQ+YjSIwMpyYY5q5VStNqv277roFUpfKvW15VJ3bSeLqU2wBcrnssLWPof0QkLhnjU7brr/E7NBmY0lMf0VHsnnkkYnqlRZIMDmXDnQukOsmV7a88VkBtIiGNHI5s+GaxSJrHUelqF/U/hIDbRoqaX6Tj+onym6luXr5yjd3hewKm3VsVKcJZtbsEYArEXDj/PYgZhpwGR485ItFgm2Y3zK0qFqFi4WYE+KzNIVEqc9oNtsPZnBkcbbaCRkjiQcFs8v84TkjIfphwZy29dw9k=
  file: ${ARTIFACT_NAME}-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true