name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v1
      - name: Set up examples
        run: |
          cp -r ./src/* ./examples/full/
          cp -r ./src/* ./examples/starter-advanced/
          cp -r ./src/* ./examples/starter-recommended/
      - name: Build test document full.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: full.tex
          working_directory: ./examples/full
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -pdflatex=lualatex -latexoption=-shell-escape
      - name: Build test document starter-advanced.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: starter-advanced.tex
          working_directory: ./examples/starter-advanced
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -pdflatex=lualatex -latexoption=-shell-escape
      - name: Build test document starter-recommended.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: starter-recommended.tex
          working_directory: ./examples/starter-recommended
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -pdflatex=lualatex -latexoption=-shell-escape
      - name: Setup Node.js for Release
        if: github.ref == 'refs/heads/master'
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies for Release
        if: github.ref == 'refs/heads/master'
        run: npm ci
      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release