name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'
      - '.gitignore'
      - '.devcontainer.json'
      - 'README.md'
      - '*.ps1'
      - '*.sh'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
    branches-ignore:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'
      - '.gitignore'
      - '.devcontainer.json'
      - 'README.md'
      - '*.ps1'
      - '*.sh'
      - 'CONTRIBUTING.md'
      - 'LICENSE'

jobs:
  test:
    name: Test building examples
    runs-on: ubuntu-18.04
    container:
      image: danteev/texlive:202006150204173dfee6
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run tests
        run: chmod +x ./test.sh && ./test.sh
      - name: Upload test artifacts (examples)
        uses: actions/upload-artifact@v2
        with:
          name: examples
          path: examples/**/*.pdf
