name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Run release procedure
    runs-on: ubuntu-18.04
    container:
      image: danteev/texlive:202006150204173dfee6
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run tests
        run: chmod +x ./test.sh && ./test.sh
      - name: Upload build artifacts (examples)
        uses: actions/upload-artifact@v2
        with:
          name: examples
          path: examples/**/*.pdf
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Release to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Docker Hub will create a new release when a new tag is created.
